### ISSUE TITLE
build error using TS 5.6

### ISSUE THREAD

**Issue by erlangxk** [Effect-TS/effect#3848]
### What version of Effect is running?

3.10.4

### What steps can reproduce the bug?

have dependency of effect ts 3.10.4 and using TS 5.6

### What is the expected behavior?

build correctly

### What do you see instead?

../../node_modules/.pnpm/effect@3.10.4/node_modules/effect/dist/dts/Utils.d.ts:69:22 - error TS2420: Class 'SingleShotGen<T, A>' incorrectly implements interface 'Generator<T, A, any>'.
  Type 'SingleShotGen<T, A>' is missing the following properties from type 'Generator<T, A, any>': map, filter, take, drop, and 9 more.

69 export declare class SingleShotGen<T, A> implements Generator<T, A> {
                        ~~~~~~~~~~~~~


Found 1 error in ../../node_modules/.pnpm/effect@3.10.4/node_modules/effect/dist/dts/Utils.d.ts:69

### Additional information

if build with TS 5.5, it's successful.

**Comment by IMax153** [comment]
@erlangxk - we had a similar issue in the Effect playground and IIRC upgrading `@types/node` solved the issue? 

But just in case I'm misremembering, I'll ping @gcanti as well :)

**Comment by zkx5xkt** [comment]
this error still exists if using `ESNext.Iterator` in `lib` option in `tsconfig`: 

```json
{
  "compilerOptions": {
    "lib": ["ESNext.Collection", "ESNext.Iterator"]
  }
}
```

versions:
- `typescript` - 5.7.2
- `@types/node` - 22.10.2
- `effect` - 3.11.9

**Comment by donflopez** [comment]
Samething happens to me, same versions and config as above. Can't get it working with recent versions of TS.

**Comment by IMax153** [comment]
@zkx5xkt @donflopez @erlangxk - can you folks do me a favor and try this snapshot build in your project and let me know if the issue persists?

```
pnpm add https://pkg.pr.new/Effect-TS/effect@eab6c6c
```

**Comment by zkx5xkt** [comment]
> @zkx5xkt @donflopez @erlangxk - can you folks do me a favor and try this snapshot build in your project and let me know if the issue persists?
> 
> ```
> pnpm add https://pkg.pr.new/Effect-TS/effect@495e3c4
> ```

I tested the snapshot build, and everything is working fine now, the issue is no longer present.
Thank you for the fix.
