### ISSUE TITLE
`it.effect.fails` doesn't exist (but docs say it does)

### ISSUE THREAD

**Issue by tyler-dot-earth** [Effect-TS/effect#5934]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

The README for `@effect/vitest` states that `it.effect.fails` is a thing: 

https://github.com/Effect-TS/effect/blob/ba9e7908a80a55f24217c88af4f7d89a4f7bc0e4/packages/vitest/README.md?plain=1#L228-L229

... but it isn't a _real_ thing as far as i can tell:

- https://github.com/search?q=repo%3AEffect-TS%2Feffect%20%22it.effect.fails%22&type=code

Locally I'm seeing:
```
Diagnostics:
1. tsserver: Property 'fails' does not exist on type 'Tester<TestServices>'. [2339]
```

I noticed after reading it on @kitlangton's effect.solutions site:
- https://www.effect.solutions/testing#expecting-tests-to-fail

Should it be a real thing? Is it a hallucination? Should it be using [a different `it.*` method](https://github.com/Effect-TS/effect/blob/main/packages/vitest/README.md#overview)?

**Comment by aymenhmaidiwastaken** [comment]
Looks like `it.effect.fails` was added in #3973 — this issue can likely be closed. However, I noticed the code example in the README has a type annotation bug: `divide` is typed as returning `number` but actually returns `Effect.Effect<number, string>`. Opening a PR to fix that.

**Comment by fubhy** [comment]
Closing as resolved: `it.effect.fails` now exists in the current `@effect/vitest` API and declarations, and the related README example fix was merged in #6163.
